blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/dovutuan/japanese-text-utils#readme
    about: Please check the documentation before creating an issue.
